logging:
  level:
    root: error
    com.pechatnikov.numbermnemocardsgeneratorbot: debug

#spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: "jdbc:postgresql://192.168.88.248:32773/mnemocards"